import 'package:flutter/material.dart';
import 'package:quran_app/quranDrawer.dart';
import 'package:quran_app/sura.dart';

void main() => runApp(const QuranApp());

class QuranApp extends StatelessWidget {
  const QuranApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Quran App',
      theme: ThemeData(
        primarySwatch: Colors.teal,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: HomePage(),
    );
  }
}

// ignore: must_be_immutable
class HomePage extends StatelessWidget {
  final List<Sura> suras = [
    Sura(
      name: 'The Holy Quran 1',
      imagePaths: [
        'assets/0001.jpg',
        'assets/0003.jpg',
        'assets/0002.jpg',
      ],
      index: 0,
    ),
    Sura(
      name: 'Al-Fatihah',
      imagePaths: [
        'assets/0004.jpg',
      ],
      index: 1,
    ),
    Sura(
      name: 'Al-Baqarah',
      imagePaths: [
        'assets/0005.jpg',
        'assets/0006.jpg',
        'assets/0007.jpg',
        'assets/0008.jpg',
        'assets/0009.jpg',
        'assets/0010.jpg',
        'assets/0011.jpg',
        'assets/0012.jpg',
        'assets/0013.jpg',
        'assets/0014.jpg',
        'assets/0015.jpg',
        'assets/0016.jpg',
        'assets/0017.jpg',
        'assets/0018.jpg',
        'assets/0019.jpg',
        'assets/0020.jpg',
        'assets/0021.jpg',
        'assets/0022.jpg',
        'assets/0023.jpg',
        'assets/0024.jpg',
        'assets/0025.jpg',
        'assets/0026.jpg',
        'assets/0027.jpg',
        'assets/0028.jpg',
        'assets/0029.jpg',
        'assets/0030.jpg',
        'assets/0031.jpg',
        'assets/0032.jpg',
        'assets/0033.jpg',
        'assets/0034.jpg',
        'assets/0035.jpg',
        'assets/0036.jpg',
        'assets/0037.jpg',
        'assets/0038.jpg',
        'assets/0039.jpg',
        'assets/0040.jpg',
        'assets/0041.jpg',
        'assets/0042.jpg',
        'assets/0043.jpg',
        'assets/0044.jpg',
        'assets/0045.jpg',
        'assets/0046.jpg',
        'assets/0047.jpg',
        'assets/0048.jpg',
        'assets/0049.jpg',
        'assets/0050.jpg',
        'assets/0051.jpg',
        'assets/0052.jpg',
      ],
      index: 2,
    ),
    Sura(
      name: 'Al-Imran',
      imagePaths: [
        'assets/0053.jpg',
        'assets/0054.jpg',
        'assets/0055.jpg',
        'assets/0056.jpg',
        'assets/0057.jpg',
        'assets/0058.jpg',
        'assets/0059.jpg',
        'assets/0060.jpg',
        'assets/0061.jpg',
        'assets/0062.jpg',
        'assets/0063.jpg',
        'assets/0064.jpg',
        'assets/0065.jpg',
        'assets/0066.jpg',
        'assets/0067.jpg',
        'assets/0068.jpg',
        'assets/0069.jpg',
        'assets/0070.jpg',
        'assets/0071.jpg',
        'assets/0072.jpg',
        'assets/0073.jpg',
        'assets/0074.jpg',
        'assets/0075.jpg',
        'assets/0076.jpg',
        'assets/0077.jpg',
        'assets/0078.jpg',
        'assets/0079.jpg',
      ],
      index: 3,
    ),
    Sura(
      name: 'An-Nisa',
      imagePaths: [
        'assets/0080.jpg',
        'assets/0081.jpg',
        'assets/0082.jpg',
        'assets/0083.jpg',
        'assets/0084.jpg',
        'assets/0085.jpg',
        'assets/0086.jpg',
        'assets/0087.jpg',
        'assets/0088.jpg',
        'assets/0089.jpg',
        'assets/0090.jpg',
        'assets/0091.jpg',
        'assets/0092.jpg',
        'assets/0093.jpg',
        'assets/0094.jpg',
        'assets/0095.jpg',
        'assets/0096.jpg',
        'assets/0097.jpg',
        'assets/0098.jpg',
        'assets/0099.jpg',
        'assets/0100.jpg',
        'assets/0101.jpg',
        'assets/0102.jpg',
        'assets/0103.jpg',
        'assets/0104.jpg',
        'assets/0105.jpg',
      ],
      index: 4,
    ),
    Sura(
      name: 'al-Maidah',
      imagePaths: [
        'assets/0106.jpg',
        'assets/0107.jpg',
        'assets/0108.jpg',
        'assets/0109.jpg',
        'assets/0110.jpg',
        'assets/0111.jpg',
        'assets/0112.jpg',
        'assets/0113.jpg',
        'assets/0114.jpg',
        'assets/0115.jpg',
        'assets/0116.jpg',
        'assets/0117.jpg',
        'assets/0118.jpg',
        'assets/0119.jpg',
        'assets/0120.jpg',
        'assets/0121.jpg',
        'assets/0122.jpg',
        'assets/0123.jpg',
        'assets/0124.jpg',
        'assets/0125.jpg',
        'assets/0126.jpg',
        'assets/0127.jpg',
        'assets/0128.jpg',
        'assets/0129.jpg',
        'assets/0130.jpg',
      ],
      index: 5,
    ),
    Sura(
      name: 'al-An`am	',
      imagePaths: [
        'assets/0131.jpg',
        'assets/0132.jpg',
        'assets/0133.jpg',
        'assets/0134.jpg',
        'assets/0135.jpg',
        'assets/0136.jpg',
        'assets/0137.jpg',
        'assets/0138.jpg',
        'assets/0139.jpg',
        'assets/0440.jpg',
        'assets/0141.jpg',
        'assets/0142.jpg',
        'assets/0143.jpg',
        'assets/0144.jpg',
        'assets/0145.jpg',
        'assets/0146.jpg',
        'assets/0147.jpg',
        'assets/0148.jpg',
        'assets/0149.jpg',
        'assets/0150.jpg',
        'assets/0151.jpg',
        'assets/0152.jpg',
        'assets/0153.jpg',
      ],
      index: 6,
    ),
    Sura(
      name: 'al-A`raf',
      imagePaths: [
        'assets/0154.jpg',
        'assets/0155.jpg',
        'assets/0156.jpg',
        'assets/0157.jpg',
        'assets/0158.jpg',
        'assets/0159.jpg',
        'assets/0160.jpg',
        'assets/0161.jpg',
        'assets/0162.jpg',
        'assets/0163.jpg',
        'assets/0164.jpg',
        'assets/0165.jpg',
        'assets/0166.jpg',
        'assets/0167.jpg',
        'assets/0168.jpg',
        'assets/0169.jpg',
        'assets/0170.jpg',
        'assets/0171.jpg',
        'assets/0172.jpg',
        'assets/0173.jpg',
        'assets/0174.jpg',
        'assets/0175.jpg',
        'assets/0176.jpg',
        'assets/0177.jpg',
        'assets/0178.jpg',
        'assets/0179.jpg',
      ],
      index: 7,
    ),
    Sura(
      name: 'al-Anfal	',
      imagePaths: [
        'assets/0180.jpg',
        'assets/0181.jpg',
        'assets/0182.jpg',
        'assets/0183.jpg',
        'assets/0184.jpg',
        'assets/0185.jpg',
        'assets/0186.jpg',
        'assets/0187.jpg',
        'assets/0188.jpg',
        'assets/0189.jpg',
      ],
      index: 8,
    ),
    Sura(
      name: 'at-Taubah	',
      imagePaths: [
        'assets/0190.jpg',
        'assets/0191.jpg',
        'assets/0192.jpg',
        'assets/0193.jpg',
        'assets/0194.jpg',
        'assets/0195.jpg',
        'assets/0196.jpg',
        'assets/0197.jpg',
        'assets/0198.jpg',
        'assets/0199.jpg',
        'assets/0200.jpg',
        'assets/0201.jpg',
        'assets/0202.jpg',
        'assets/0203.jpg',
        'assets/0204.jpg',
        'assets/0205.jpg',
        'assets/0206.jpg',
        'assets/0207.jpg',
        'assets/0208.jpg',
        'assets/0209.jpg',
        'assets/0210.jpg',
      ],
      index: 9,
    ),
    Sura(
      name: 'Yunus',
      imagePaths: [
        'assets/0211.jpg',
        'assets/0212.jpg',
        'assets/0213.jpg',
        'assets/0214.jpg',
        'assets/0215.jpg',
        'assets/0216.jpg',
        'assets/0217.jpg',
        'assets/0218.jpg',
        'assets/0219.jpg',
        'assets/0220.jpg',
      ],
      index: 10,
    ),
    Sura(
      name: 'Hud',
      imagePaths: [
        'assets/0221.jpg',
        'assets/0222.jpg',
        'assets/0223.jpg',
        'assets/0224.jpg',
        'assets/0225.jpg',
        'assets/0226.jpg',
        'assets/0227.jpg',
        'assets/0228.jpg',
        'assets/0229.jpg',
        'assets/0230.jpg',
        'assets/0231.jpg',
        'assets/0232.jpg',
        'assets/0233.jpg',
        'assets/0234.jpg',
        'assets/0235.jpg',
      ],
      index: 11,
    ),
    Sura(
      name: 'Yusuf',
      imagePaths: [
        'assets/0236.jpg',
        'assets/0237.jpg',
        'assets/0238.jpg',
        'assets/0239.jpg',
        'assets/0240.jpg',
        'assets/0241.jpg',
        'assets/0242.jpg',
        'assets/0243.jpg',
        'assets/0244.jpg',
        'assets/0245.jpg',
        'assets/0246.jpg',
        'assets/0247.jpg',
        'assets/0248.jpg',
        'assets/0249.jpg',
        'assets/0250.jpg',
        'assets/0251.jpg',
      ],
      index: 12,
    ),
    Sura(
      name: 'ar-Ra`d	',
      imagePaths: [
        'assets/0252.jpg',
        'assets/0253.jpg',
        'assets/0254.jpg',
        'assets/0255.jpg',
        'assets/0256.jpg',
        'assets/0257.jpg',
      ],
      index: 13,
    ),
    Sura(
      name: 'Ibrahim',
      imagePaths: [
        'assets/0258.jpg',
        'assets/0259.jpg',
        'assets/0260.jpg',
        'assets/0261.jpg',
        'assets/0262.jpg',
        'assets/0263.jpg',
        'assets/0264.jpg',
      ],
      index: 14,
    ),
    Sura(
      name: 'al-Hijr	',
      imagePaths: [
        'assets/0265.jpg',
        'assets/0266.jpg',
        'assets/0267.jpg',
        'assets/0268.jpg',
        'assets/0269.jpg',
      ],
      index: 15,
    ),
    Sura(
      name: 'an-Nahl	',
      imagePaths: [
        'assets/0270.jpg',
        'assets/0271.jpg',
        'assets/0272.jpg',
        'assets/0273.jpg',
        'assets/0274.jpg',
        'assets/0275.jpg',
        'assets/0276.jpg',
        'assets/0277.jpg',
        'assets/0278.jpg',
        'assets/0279.jpg',
        'assets/0280.jpg',
        'assets/0281.jpg',
        'assets/0282.jpg',
        'assets/0283.jpg',
        'assets/0284.jpg',
      ],
      index: 16,
    ),
    Sura(
      name: 'Al-Isra	',
      imagePaths: [
        'assets/0285.jpg',
        'assets/0286.jpg',
        'assets/0287.jpg',
        'assets/0288.jpg',
        'assets/0289.jpg',
        'assets/0290.jpg',
        'assets/0291.jpg',
        'assets/0292.jpg',
        'assets/0293.jpg',
        'assets/0294.jpg',
        'assets/0295.jpg',
        'assets/0296.jpg',
      ],
      index: 17,
    ),
    Sura(
      name: 'al-Kahf	',
      imagePaths: [
        'assets/0297.jpg',
        'assets/0298.jpg',
        'assets/0299.jpg',
        'assets/0300.jpg',
        'assets/0301.jpg',
        'assets/0302.jpg',
        'assets/0303.jpg',
        'assets/0304.jpg',
        'assets/0305.jpg',
        'assets/0306.jpg',
        'assets/0307.jpg',
      ],
      index: 18,
    ),
    Sura(
      name: 'Maryam	',
      imagePaths: [
        'assets/0308.jpg',
        'assets/0309.jpg',
        'assets/0310.jpg',
        'assets/0311.jpg',
        'assets/0312.jpg',
        'assets/0313.jpg',
        'assets/0314.jpg',
      ],
      index: 19,
    ),
    Sura(
      name: 'Ta Ha	',
      imagePaths: [
        'assets/0315.jpg',
        'assets/0316.jpg',
        'assets/0317.jpg',
        'assets/0318.jpg',
        'assets/0319.jpg',
        'assets/0320.jpg',
        'assets/0321.jpg',
        'assets/0322.jpg',
        'assets/0323.jpg',
        'assets/0324.jpg',
      ],
      index: 20,
    ),
    Sura(
      name: 'al-Anbiya',
      imagePaths: [
        'assets/0325.jpg',
        'assets/0326.jpg',
        'assets/0327.jpg',
        'assets/0328.jpg',
        'assets/0329.jpg',
        'assets/0330.jpg',
        'assets/0331.jpg',
        'assets/0332.jpg',
        'assets/0333.jpg',
        'assets/0334.jpg',
      ],
      index: 21,
    ),
    Sura(
      name: 'al-Hajj',
      imagePaths: [
        'assets/0335.jpg',
        'assets/0336.jpg',
        'assets/0337.jpg',
        'assets/0338.jpg',
        'assets/0339.jpg',
        'assets/0340.jpg',
        'assets/0341.jpg',
        'assets/0342.jpg',
        'assets/0343.jpg',
        'assets/0344.jpg',
      ],
      index: 22,
    ),
    Sura(
      name: '	al-Mu\'minun	',
      imagePaths: [
        'assets/0345.jpg',
        'assets/0346.jpg',
        'assets/0347.jpg',
        'assets/0348.jpg',
        'assets/0349.jpg',
        'assets/0350.jpg',
        'assets/0351.jpg',
        'assets/0352.jpg',
      ],
      index: 23,
    ),
    Sura(
      name: 'an-Nur	',
      imagePaths: [
        'assets/0353.jpg',
        'assets/0354.jpg',
        'assets/0355.jpg',
        'assets/0356.jpg',
        'assets/0357.jpg',
        'assets/0358.jpg',
        'assets/0359.jpg',
        'assets/0360.jpg',
        'assets/0361.jpg',
        'assets/0362.jpg',
      ],
      index: 24,
    ),
    Sura(
      name: 'al-Furqan	',
      imagePaths: [
        'assets/0363.jpg',
        'assets/0364.jpg',
        'assets/0365.jpg',
        'assets/0366.jpg',
        'assets/0367.jpg',
        'assets/0368.jpg',
        'assets/0369.jpg',
      ],
      index: 25,
    ),
    Sura(
      name: 'ash-Shu\`ara',
      imagePaths: [
        'assets/0370.jpg',
        'assets/0371.jpg',
        'assets/0372.jpg',
        'assets/0373.jpg',
        'assets/0374.jpg',
        'assets/0375.jpg',
        'assets/0376.jpg',
        'assets/0377.jpg',
        'assets/0378.jpg',
        'assets/0379.jpg',
      ],
      index: 26,
    ),
    Sura(
      name: 'an-Naml	',
      imagePaths: [
        'assets/0380.jpg',
        'assets/0381.jpg',
        'assets/0382.jpg',
        'assets/0383.jpg',
        'assets/0384.jpg',
        'assets/0385.jpg',
        'assets/0386.jpg',
        'assets/0387.jpg',
        'assets/0388.jpg',
      ],
      index: 27,
    ),
    Sura(
      name: 'al-Qasas	',
      imagePaths: [
        'assets/0389.jpg',
        'assets/0390.jpg',
        'assets/0391.jpg',
        'assets/0392.jpg',
        'assets/0393.jpg',
        'assets/0394.jpg',
        'assets/0395.jpg',
        'assets/0396.jpg',
        'assets/0397.jpg',
        'assets/0398.jpg',
        'assets/0399.jpg',
      ],
      index: 28,
    ),
    Sura(
      name: 'al-`Ankabut	',
      imagePaths: [
        'assets/0400.jpg',
        'assets/0401.jpg',
        'assets/0402.jpg',
        'assets/0403.jpg',
        'assets/0404.jpg',
        'assets/0405.jpg',
        'assets/0406.jpg',
        'assets/0407.jpg',
      ],
      index: 29,
    ),
    Sura(
      name: 'ar-Rum	',
      imagePaths: [
        'assets/0408.jpg',
        'assets/0409.jpg',
        'assets/0410.jpg',
        'assets/0411.jpg',
        'assets/0412.jpg',
        'assets/0413.jpg',
      ],
      index: 30,
    ),
    Sura(
      name: 'Luqman	',
      imagePaths: [
        'assets/0414.jpg',
        'assets/0415.jpg',
        'assets/0416.jpg',
        'assets/0417.jpg',
      ],
      index: 31,
    ),
    Sura(
      name: 'as-Sajdah	',
      imagePaths: [
        'assets/0418.jpg',
        'assets/0419.jpg',
        'assets/0420.jpg',
      ],
      index: 32,
    ),
    Sura(
      name: 'al-Ahzab	',
      imagePaths: [
        'assets/0421.jpg',
        'assets/0422.jpg',
        'assets/0423.jpg',
        'assets/0424.jpg',
        'assets/0425.jpg',
        'assets/0426.jpg',
        'assets/0427.jpg',
        'assets/0428.jpg',
        'assets/0429.jpg',
        'assets/0430.jpg',
      ],
      index: 33,
    ),
    Sura(
      name: 'Saba',
      imagePaths: [
        'assets/0431.jpg',
        'assets/0432.jpg',
        'assets/0433.jpg',
        'assets/0434.jpg',
        'assets/0435.jpg',
        'assets/0436.jpg',
        'assets/0437.jpg',
      ],
      index: 34,
    ),
    Sura(
      name: 'Fatir	',
      imagePaths: [
        'assets/0438.jpg',
        'assets/0439.jpg',
        'assets/0440.jpg',
        'assets/0441.jpg',
        'assets/0442.jpg',
      ],
      index: 35,
    ),
    Sura(
      name: 'Ya Sin	',
      imagePaths: [
        'assets/0443.jpg',
        'assets/0444.jpg',
        'assets/0445.jpg',
        'assets/0446.jpg',
        'assets/0447.jpg',
        'assets/0448.jpg',
      ],
      index: 36,
    ),
    Sura(
      name: 'as-Saffat	',
      imagePaths: [
        'assets/0449.jpg',
        'assets/0450.jpg',
        'assets/0451.jpg',
        'assets/0452.jpg',
        'assets/0453.jpg',
        'assets/0454.jpg',
        'assets/0455.jpg',
      ],
      index: 37,
    ),
    Sura(
      name: 'Sad	',
      imagePaths: [
        'assets/0456.jpg',
        'assets/0457.jpg',
        'assets/0458.jpg',
        'assets/0459.jpg',
        'assets/0460.jpg',
      ],
      index: 38,
    ),
    Sura(
      name: 'az-Zumar	',
      imagePaths: [
        'assets/0461.jpg',
        'assets/0462.jpg',
        'assets/0463.jpg',
        'assets/0464.jpg',
        'assets/0465.jpg',
        'assets/0466.jpg',
        'assets/0467.jpg',
        'assets/0468.jpg',
        'assets/0469.jpg',
      ],
      index: 39,
    ),
    Sura(
      name: 'Ghafir	',
      imagePaths: [
        'assets/0470.jpg',
        'assets/0471.jpg',
        'assets/0472.jpg',
        'assets/0473.jpg',
        'assets/0474.jpg',
        'assets/0475.jpg',
        'assets/0476.jpg',
        'assets/0477.jpg',
        'assets/0478.jpg',
        'assets/0479.jpg',
      ],
      index: 40,
    ),
    Sura(
      name: 'Fussilat	',
      imagePaths: [
        'assets/0480.jpg',
        'assets/0481.jpg',
        'assets/0482.jpg',
        'assets/0483.jpg',
        'assets/0484.jpg',
        'assets/0485.jpg',
      ],
      index: 41,
    ),
    Sura(
      name: 'ash-Shura	',
      imagePaths: [
        'assets/0486.jpg',
        'assets/0487.jpg',
        'assets/0488.jpg',
        'assets/0489.jpg',
        'assets/0490.jpg',
        'assets/0491.jpg',
      ],
      index: 42,
    ),
    Sura(
      name: 'az-Zukhruf	',
      imagePaths: [
        'assets/0492.jpg',
        'assets/0493.jpg',
        'assets/0494.jpg',
        'assets/0495.jpg',
        'assets/0496.jpg',
        'assets/0497.jpg',
        'assets/0498.jpg',
      ],
      index: 43,
    ),
    Sura(
      name: 'ad-Dukhan	',
      imagePaths: [
        'assets/0499.jpg',
        'assets/0500.jpg',
        'assets/0501.jpg',
      ],
      index: 44,
    ),
    Sura(
      name: 'al-Jathiyah	',
      imagePaths: [
        'assets/0502.jpg',
        'assets/0503.jpg',
        'assets/0504.jpg',
      ],
      index: 45,
    ),
    Sura(
      name: 'al-Ahqaf	',
      imagePaths: [
        'assets/0505.jpg',
        'assets/0506.jpg',
        'assets/0507.jpg',
        'assets/0508.jpg',
        'assets/0509.jpg',
      ],
      index: 46,
    ),
    Sura(
      name: 'Muhammad	',
      imagePaths: [
        'assets/0510.jpg',
        'assets/0511.jpg',
        'assets/0512.jpg',
        'assets/0513.jpg',
      ],
      index: 47,
    ),
    Sura(
      name: 'al-Fath	',
      imagePaths: [
        'assets/0514.jpg',
        'assets/0515.jpg',
        'assets/0516.jpg',
        'assets/0517.jpg',
      ],
      index: 48,
    ),
    Sura(
      name: 'al-Hujurat	',
      imagePaths: [
        'assets/0518.jpg',
        'assets/0519.jpg',
        'assets/0520.jpg',
      ],
      index: 49,
    ),
    Sura(
      name: 'Qaf',
      imagePaths: [
        'assets/0521.jpg',
        'assets/0522.jpg',
        'assets/0523.jpg',
      ],
      index: 50,
    ),
    Sura(
      name: 'ad-Dhariyat	',
      imagePaths: [
        'assets/0524.jpg',
        'assets/0525.jpg',
        'assets/0526.jpg',
      ],
      index: 51,
    ),
    Sura(
      name: 'at-Tur	',
      imagePaths: [
        'assets/0527.jpg',
        'assets/0528.jpg',
      ],
      index: 52,
    ),
    Sura(
      name: 'an-Najm	',
      imagePaths: [
        'assets/0529.jpg',
        'assets/0530.jpg',
        'assets/0531.jpg',
      ],
      index: 53,
    ),
    Sura(
      name: 'al-Qamar	',
      imagePaths: [
        'assets/0532.jpg',
        'assets/0533.jpg',
      ],
      index: 54,
    ),
    Sura(
      name: 'ar-Rahman	',
      imagePaths: [
        'assets/0534.jpg',
        'assets/0535.jpg',
        'assets/0536.jpg',
      ],
      index: 55,
    ),
    Sura(
      name: 'al-Waqi`ah	',
      imagePaths: [
        'assets/0537.jpg',
        'assets/0538.jpg',
        'assets/0539.jpg',
        'assets/0540.jpg',
      ],
      index: 56,
    ),
    Sura(
      name: 'al-Hadid	',
      imagePaths: [
        'assets/0541.jpg',
        'assets/0542.jpg',
        'assets/0543.jpg',
        'assets/0544.jpg',
      ],
      index: 57,
    ),
    Sura(
      name: 'al-Mujadilah	',
      imagePaths: [
        'assets/0545.jpg',
        'assets/0546.jpg',
        'assets/0547.jpg',
      ],
      index: 58,
    ),
    Sura(
      name: 'al-Hashr	',
      imagePaths: [
        'assets/0548.jpg',
        'assets/0549.jpg',
        'assets/0550.jpg',
        'assets/0551.jpg',
      ],
      index: 59,
    ),
    Sura(
      name: 'al-Mumtahanah	',
      imagePaths: [
        'assets/0552.jpg',
        'assets/0553.jpg',
      ],
      index: 60,
    ),
    Sura(
      name: 'as-Saff	',
      imagePaths: [
        'assets/0554.jpg',
        'assets/0555.jpg',
      ],
      index: 61,
    ),
    Sura(
      name: 'al-Jumu`ah	',
      imagePaths: [
        'assets/0556.jpg',
      ],
      index: 62,
    ),
    Sura(
      name: 'al-Munafiqun	',
      imagePaths: [
        'assets/0557.jpg',
        'assets/0558.jpg',
      ],
      index: 63,
    ),
    Sura(
      name: 'at-Taghabun	',
      imagePaths: [
        'assets/0559.jpg',
        'assets/0560.jpg',
      ],
      index: 64,
    ),
    Sura(
      name: 'at-Talaq,	',
      imagePaths: [
        'assets/0561.jpg',
        'assets/0562.jpg',
      ],
      index: 65,
    ),
    Sura(
      name: 'at-Tahrim	',
      imagePaths: [
        'assets/0563.jpg',
        'assets/0564.jpg',
      ],
      index: 66,
    ),
    Sura(
      name: 'al-Mulk	',
      imagePaths: [
        'assets/0565.jpg',
        'assets/0566.jpg',
      ],
      index: 67,
    ),
    Sura(
      name: 'al-Qalam	',
      imagePaths: [
        'assets/0567.jpg',
        'assets/0568.jpg',
        'assets/0569.jpg',
      ],
      index: 68,
    ),
    Sura(
      name: 'al-Haqqah	',
      imagePaths: [
        'assets/0570.jpg',
        'assets/0571.jpg',
      ],
      index: 69,
    ),
    Sura(
      name: 'al-Ma`arij	',
      imagePaths: [
        'assets/0572.jpg',
      ],
      index: 70,
    ),
    Sura(
      name: 'Nuh',
      imagePaths: [
        'assets/0573.jpg',
        'assets/0574.jpg',
      ],
      index: 71,
    ),
    Sura(
      name: 'al-Jinn	',
      imagePaths: [
        'assets/0575.jpg',
        'assets/0576.jpg',
      ],
      index: 72,
    ),
    Sura(
      name: 'al-Muzammil	',
      imagePaths: [
        'assets/0577.jpg',
      ],
      index: 73,
    ),
    Sura(
      name: 'al-Mudathir	',
      imagePaths: [
        'assets/0578.jpg',
        'assets/0579.jpg',
      ],
      index: 74,
    ),
    Sura(
      name: 'al-Qiyamah	',
      imagePaths: [
        'assets/0580.jpg',
        'assets/0581.jpg',
      ],
      index: 75,
    ),
    Sura(
      name: 'al-Insane	',
      imagePaths: [
        'assets/0582.jpg',
      ],
      index: 76,
    ),
    Sura(
      name: 'al-Mursalat	',
      imagePaths: [
        'assets/0583.jpg',
        'assets/0584.jpg',
      ],
      index: 77,
    ),
    Sura(
      name: 'an-Naba',
      imagePaths: [
        'assets/0585.jpg',
        'assets/0586.jpg',
      ],
      index: 78,
    ),
    Sura(
      name: 'an-Nazi`at	',
      imagePaths: [
        'assets/0587.jpg',
      ],
      index: 79,
    ),
    Sura(
      name: '`Abasa	',
      imagePaths: [
        'assets/0588.jpg',
      ],
      index: 80,
    ),
    Sura(
      name: 'at-Takwir	',
      imagePaths: [
        'assets/0589.jpg',
      ],
      index: 81,
    ),
    Sura(
      name: 'al-Infitar	',
      imagePaths: [
        'assets/0590.jpg',
      ],
      index: 82,
    ),
    Sura(
      name: 'Al-Mutaffifeen	',
      imagePaths: [
        'assets/0591.jpg',
      ],
      index: 83,
    ),
    Sura(
      name: 'al-Inshiqaq	',
      imagePaths: [
        'assets/0592.jpg',
      ],
      index: 84,
    ),
    Sura(
      name: 'al-Buruj	',
      imagePaths: [
        'assets/0593.jpg',
      ],
      index: 85,
    ),
    Sura(
      name: 'at-Tariq	 al-A`la',
      imagePaths: [
        'assets/0594.jpg',
      ],
      index: 86,
    ),
    Sura(
      name: 'al-Ghashiya	',
      imagePaths: [
        'assets/0595.jpg',
      ],
      index: 87,
    ),
    Sura(
      name: 'al-Fajr	',
      imagePaths: [
        'assets/0596.jpg',
      ],
      index: 89,
    ),
    Sura(
      name: 'al-Balad	',
      imagePaths: [
        'assets/0597.jpg',
      ],
      index: 90,
    ),
    Sura(
      name: 'al-Shams	al-Layl',
      imagePaths: [
        'assets/0598.jpg',
      ],
      index: 91,
    ),
    Sura(
      name: 'ad-Duha	ash-Sharh',
      imagePaths: [
        'assets/0599.jpg',
      ],
      index: 92,
    ),
    Sura(
      name: 'at-Tin	al-`Alaq',
      imagePaths: [
        'assets/0600.jpg',
      ],
      index: 93,
    ),
    Sura(
      name: 'al-qadr	al-Bayyinah',
      imagePaths: [
        'assets/0601.jpg',
      ],
      index: 94,
    ),
    Sura(
      name: 'Az-Zalzala  al-`Adiyat	',
      imagePaths: [
        'assets/0602.jpg',
      ],
      index: 95,
    ),
    Sura(
      name: 'al-Qari`ah	at-Takathur',
      imagePaths: [
        'assets/0603.jpg',
      ],
      index: 96,
    ),
    Sura(
      name: 'al-`Asr	al-Humazah al-Fil',
      imagePaths: [
        'assets/0604.jpg',
      ],
      index: 97,
    ),
    Sura(
      name: 'al-Quraish	al-Ma`un al-Kauthar',
      imagePaths: [
        'assets/0605.jpg',
      ],
      index: 98,
    ),
    Sura(
      name: 'al-Kafirun	an-Nasr Al-Masad',
      imagePaths: [
        'assets/0606.jpg',
      ],
      index: 99,
    ),
    Sura(
      name: 'al-Ikhlas	al-Falaq an-Nas',
      imagePaths: [
        'assets/0607.jpg',
      ],
      index: 100,
    ),
    Sura(
      name: 'content of Quran	',
      imagePaths: [
        'assets/0608.jpg',
        'assets/0609.jpg',
        'assets/0610.jpg',
        'assets/0611.jpg',
        'assets/0612.jpg',
        'assets/0613.jpg',
        'assets/0614.jpg',
        'assets/0615.jpg',
        'assets/0616.jpg',
        'assets/0617.jpg',
        'assets/0618.jpg',
        'assets/0619.jpg',
        'assets/0620.jpg',
        'assets/0621.jpg',
        'assets/0622.jpg',
        'assets/0623.jpg',
        'assets/0624.jpg',
        'assets/0625.jpg',
        'assets/0626.jpg',
      ],
      index: 100,
    ),
  ];

  HomePage({super.key});
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text(
          'القران الكريم ',
          style: TextStyle(fontWeight: FontWeight.bold, fontSize: 25),
        ),
        centerTitle: true,
      ),
      drawer: QuranDrawer(suras: suras),
      body: ListView.builder(
        itemCount: suras.length,
        itemBuilder: (context, index) {
          final sura = suras[index];
          final imageWidgets = sura.imagePaths
              .map((imagePath) => Image.asset(imagePath))
              .toList();
          return Column(
            mainAxisAlignment: MainAxisAlignment.center,
            crossAxisAlignment: CrossAxisAlignment.center,
            children: [
              Text(
                ' ${sura.name}',
                textAlign: TextAlign.center,
                style: Theme.of(context).textTheme.headlineMedium,
              ),
              const SizedBox(height: 8),
              ...imageWidgets,
              const SizedBox(height: 16),
            ],
          );
        },
      ),
    );
  }
}
